name: CI

on:
  pull_request:
    branches: [ main ]
  workflow_call: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm ci
      - run: npm run gulp
      - run: npm run lint
