name: Github -> snowgo.at deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: tallboy/snowgo.at/.github/workflows/ci.yml@main

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.2.11
      env:
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_USER: ${{ secrets.SSH_USERNAME }}
        REMOTE_PORT: ${{ secrets.SSH_PORT }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        SOURCE: "dist/"
        TARGET: "/usr/share/nginx/html/snowgo.at"
        ARGS: "-avzr --delete"
